### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by phackstock**
# Pull request

This PR updates the following dependencies to the currently latest versions:

* scmdata
* pandas (to version 2)
* pyam-iamc
* pytest

the biggest change is pandas 2 which broke a number of tests.
I have done my best to implement fixes related to deprecated pandas functionality.
There's still currently a couple of tests failing on my machine. 
They are:
* `test_load_rewritten_scen7` failing because there's two warnings instead of one
* ~~`test_writing_identical_rcpdat` all the tests with `add_extra_data = True` are failing~~ (fixed per 2af4eb1)
* `test_default_config` and `test_readme` seem to be failing because I don't have wine installed. I tried to install it but somehow my antivirus marks it as a virus and does not let me install it. 

- [ ] ~~Tests added~~
- [ ] ~~Documentation added (where applicable)~~
- [ ] ~~Example added (either to an existing notebook or as a new notebook, where applicable)~~
- [ ] Description in ``CHANGELOG.rst`` added

@znicholls or @lewisjared I checked _Allow edits by maintainers_ in case you have time to take a look. Could be easier for you to fix the remaining failing tests.

### CODE REVIEW

**Comment by znicholls** [comment]
Awesome. I've got to do some other work but I can then take a look at getting the CI running again and see where we end up...

**Comment by phackstock** [comment]
Looks like we'll have to way goodbye to python3.7 and 3.8 with this PR as scmdata 0.16.1 requires >=3.9.

**Comment by znicholls** [comment]
Alright @phackstock here goes nothing

**Comment by znicholls** [comment]
Thanks for your help getting this started, still lots to do but that's a job for another day

**Pull request merged**
