### PR TITLE
Update Dockerfile and remove demo

### PR DESCRIPTION
**Pull request by rgieseke**
- trying to fix the Example running on Mybinder to use the latest Pre-Release (current install uses v1.3)
- remove the Demo as it uses v1.3 syntax

### CODE REVIEW

**Comment by rgieseke** [comment]
Tested as https://mybinder.org/v2/gh/openscm/pymagicc/ba34e017ced49160dcd5024d09b2c9c4ceccde55?filepath=notebooks%2FExample.ipynb

There is an issue with `pandas-pint` not being compatible with Pandas 1.2, so i pinned Pandas.
```
File "/home/robert/Work/pymagicc/venv/lib/python3.8/site-packages/pint_pandas/pint_array.py", line 617, in _create_method
    op_name = ops._get_op_name(op, True)
AttributeError: module 'pandas.core.ops' has no attribute '_get_op_name'
```

**Comment by rgieseke** [comment]
Issue in `pint-pandas`
https://github.com/hgrecco/pint-pandas/issues/51

**Review by znicholls — APPROVED** [review]
Tidy

**Comment by rgieseke** [comment]
Pinned on scmdata now (thank for fixing it over there!)

**Pull request merged**
