### PR TITLE
Add link to AR6 region acronym definitions

### PR DESCRIPTION
**Pull request by znicholls**
# Pull request

Please confirm that this pull request has done the following:

- [x] Tests added
- [ ] Documentation added
- [x] Example added (either to an existing notebook or as a new notebook, where applicable) (N/A)
- [x] Description in ``CHANGELOG.rst`` added

## Adding to CHANGELOG.rst

Please add a single line in the changelog notes similar to one of the following:

```
- (`#XX <http://link-to-pr.com>`_) Added feature which does something
- (`#XX <http://link-to-pr.com>`_) Fixed bug identified in (`#XX <http://link-to-issue.com>`_)
```

### CODE REVIEW

**Comment by znicholls** [comment]
If AR6 regions are included, the file now looks like

```
---- HEADER ----

Test mag file
For more information on the AR6 regions (including mapping the abbrevations to their full names), see: https://github.com/SantanderMetGroup/ATLAS/tree/master/reference-regions, specifically https://github.com/SantanderMetGroup/ATLAS/blob/master/reference-regions/IPCC-WGI-reference-regions-v4_coordinates.csv (paper is at https://doi.org/10.5194/essd-2019-258)

---- METADATA ----

other info: checking time point handling

&THISFILE_SPECIFICATIONS
    THISFILE_DATACOLUMNS = 5
    THISFILE_DATAROWS = 15
    THISFILE_FIRSTYEAR = 2099
    THISFILE_LASTYEAR = 2101
    THISFILE_ANNUALSTEPS = 0
    THISFILE_DATTYPE = 'MAG'
    THISFILE_REGIONMODE = 'NONE'
    THISFILE_TIMESERIESTYPE = 'MONTHLY'
    THISFILE_FIRSTDATAROW = 26
/

   VARIABLE                 NPP                 NPP                 NPP                 NPP                 NPP
       TODO                 SET                 SET                 SET                 SET                 SET
      UNITS             gCperyr             gCperyr             gCperyr             gCperyr             gCperyr
      YEARS               WORLD             AR6-ARO             AR6-NEN                LAND               OCEAN
2099.042000         0.00000e+00         1.00000e+00         2.00000e+00         3.00000e+00         4.00000e+00
2099.125000         5.00000e+00         6.00000e+00         7.00000e+00         8.00000e+00         9.00000e+00
2099.208000         1.00000e+01         1.10000e+01         1.20000e+01         1.30000e+01         1.40000e+01
2099.292000         1.50000e+01         1.60000e+01         1.70000e+01         1.80000e+01         1.90000e+01
```

**Review by lewisjared — APPROVED** [review]
Looks great. Are you wanting to add more documentation or is it good to go?

**Comment by znicholls** [comment]
> Are you wanting to add more documentation or is it good to go?

Not sure, what do you think? e.g. do we need to document this behaviour of adding lines to headers (also now that I think about it, if you read and re-wrote files repeatedly that line would be added over and over again which isn't ideal)?

**Comment by lewisjared** [comment]
I'm not sure how we would document that other than embedding an example of each of the MAGICC files into the docs. That's a job that probably needs to be done eventually.

Good pickup re the additional lines

**Comment by znicholls** [comment]
Yes or throwing a warning, one for another day

**Pull request merged**
